name: dbus_annotations_build_runner
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/lucifdch/dbus_annotations_build_runner.dart

environment:
  sdk: '>3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  build: ^4.0.3
  dart_style: ^3.1.3
  glob: ^2.1.3
  analyzer: ^9.0.0
  source_gen: ^4.1.1

  dbus: '>0.7.0 <0.8.0'
  dbus_annotations: 0.1.0

dev_dependencies:
  lints: ^6.0.0
  analyzer: ^9.0.0
